### PR TITLE
WIP: Add luxon date checks

### PR DESCRIPTION
**Pull request by selamanse**
Solves #2

### CODE REVIEW

**Comment by selamanse** [comment]
Still needs some test coverage

@narze how exactly are the unit tests executed? do i need to run this with wrangler?

If you want me to add test coverage in this pr I need to move SUPABASE_KEY to some sort of env (or I don't know how it works)

**Comment by selamanse** [comment]
@narze can you please add the hacktoberfest-accepted label to this PR? I will continue working on this tomorrow.

**Comment by narze** [comment]
Sure thing!
For the ENV I already tried `dotenv` but it does not work for me as well, I never used Cloudflare Pages before so I'm not sure what's the best way to setup the ENV files.

**Comment by narze** [comment]
Closing this since https://github.com/narze/poppoll does not call this endpoint anymore.

**Comment by selamanse** [comment]
Ok, Do you still Need help with those env files @narze?

**Pull request closed without merging**
